version: '3.8'

services:
  pgdb:
    container_name: pgdb
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always

  redis:
    container_name: redise
    image: redis
    ports:
      - "6379:6379"