# Generated by Django 4.0.2 on 2022-03-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_category_is_sub_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='format: required, max-100', max_length=150, unique=True, verbose_name='category safe URL'),
        ),
    ]
