# Generated by Django 4.0.2 on 2022-03-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='format Y-m-d H:M:S', verbose_name='date product last updated'),
        ),
    ]
