# Generated by Django 4.0.3 on 2022-03-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(blank=True, default=None, help_text='format: not required', null=True, verbose_name='Discount coupon percentage'),
        ),
    ]
